# Generated by Django 5.0.3 on 2025-05-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
